// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TCoach
{
    public int FCoachID { get; set; }

    public bool FIsPublished { get; set; }

    public string FCoachCode { get; set; }

    public string FCoachName { get; set; }

    public byte FCoachLevelID { get; set; }

    public DateOnly FHireDate { get; set; }

    public DateOnly? FFireDate { get; set; }

    public string FPhone { get; set; }

    public DateOnly FBirthDate { get; set; }

    public string FEmail { get; set; }

    public virtual TCoachLevel FCoachLevel { get; set; }
}