// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TCoachLevel
{
    public byte FCoachLevelID { get; set; }

    public string FLevelName { get; set; }

    public virtual ICollection<TCoachPrice> TCoachPrices { get; set; } = new List<TCoachPrice>();

    public virtual ICollection<TCoach> TCoaches { get; set; } = new List<TCoach>();
}