// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TEmployeeLoginRecord
{
    public int FLoginID { get; set; }

    public int FEmployeeID { get; set; }

    public string FIPAddress { get; set; }

    public DateTime FLoginDatetime { get; set; }

    public DateTime? FLogoutDatetime { get; set; }

    public virtual TEmployee FEmployee { get; set; }
}