// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TLocation
{
    public byte FLocationID { get; set; }

    public string FLocationName { get; set; }

    public virtual ICollection<TMemberShoppingCartCourse> TMemberShoppingCartCourses { get; set; } = new List<TMemberShoppingCartCourse>();

    public virtual ICollection<TMemberShoppingCartHomestay> TMemberShoppingCartHomestayFDropoffLocations { get; set; } = new List<TMemberShoppingCartHomestay>();

    public virtual ICollection<TMemberShoppingCartHomestay> TMemberShoppingCartHomestayFPickupLocations { get; set; } = new List<TMemberShoppingCartHomestay>();

    public virtual ICollection<TOrderDetailCourse> TOrderDetailCourses { get; set; } = new List<TOrderDetailCourse>();

    public virtual ICollection<TOrderDetailHomestay> TOrderDetailHomestayFDropoffLocations { get; set; } = new List<TOrderDetailHomestay>();

    public virtual ICollection<TOrderDetailHomestay> TOrderDetailHomestayFPickupLocations { get; set; } = new List<TOrderDetailHomestay>();

    public virtual ICollection<TProductHomestay> TProductHomestays { get; set; } = new List<TProductHomestay>();

    public virtual ICollection<TProductShuttlePrice> TProductShuttlePriceFDropoffLocations { get; set; } = new List<TProductShuttlePrice>();

    public virtual ICollection<TProductShuttlePrice> TProductShuttlePriceFPickupLocations { get; set; } = new List<TProductShuttlePrice>();
}