// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TMemberNon
{
    public int FMemberNonID { get; set; }

    public string FMemberNonName { get; set; }

    public string FCountryCode { get; set; }

    public string FPhone { get; set; }

    public string FEmail { get; set; }

    public byte FPermissions { get; set; }
}