// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TMember
{
    public int FMemberID { get; set; }

    public string FMemberCode { get; set; }

    public byte FSkiLevelID { get; set; }

    public string FMemberName { get; set; }

    public string FGender { get; set; }

    public DateOnly? FBirthdate { get; set; }

    public string FCountryCode { get; set; }

    public string FPhone { get; set; }

    public string FEmail { get; set; }

    public byte FPermissions { get; set; }

    public virtual TMemberSkiLevel FSkiLevel { get; set; }

    public virtual ICollection<TMemberLoginRecord> TMemberLoginRecords { get; set; } = new List<TMemberLoginRecord>();

    public virtual ICollection<TMemberReview> TMemberReviews { get; set; } = new List<TMemberReview>();

    public virtual ICollection<TMemberShoppingCart> TMemberShoppingCarts { get; set; } = new List<TMemberShoppingCart>();

    public virtual ICollection<TMemberThirdPartyAccount> TMemberThirdPartyAccounts { get; set; } = new List<TMemberThirdPartyAccount>();

    public virtual ICollection<TMemberWebsiteAccount> TMemberWebsiteAccounts { get; set; } = new List<TMemberWebsiteAccount>();

    public virtual ICollection<TOrder> TOrders { get; set; } = new List<TOrder>();
}