// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TMemberLoginRecord
{
    public int FLoginRecordID { get; set; }

    public int FMemberID { get; set; }

    public byte FLoginTypeID { get; set; }

    public string FLoginTimezone { get; set; }

    public string FLoginIPAddress { get; set; }

    public DateTime FLoginDatetime { get; set; }

    public DateTime? FLogoutDatetime { get; set; }

    public virtual TMemberLoginType FLoginType { get; set; }

    public virtual TMember FMember { get; set; }
}