// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TMemberWebsiteAccount
{
    public int FWebsiteAccountID { get; set; }

    public int FMemberID { get; set; }

    public string FAccount { get; set; }

    public byte[] FPasswordHash { get; set; }

    public byte[] FPasswordSalt { get; set; }

    public virtual TMember FMember { get; set; }
}