// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TMemberReview
{
    public int FReviewID { get; set; }

    public int FMemberID { get; set; }

    public string FProductType { get; set; }

    public int FProductID { get; set; }

    public DateOnly? FReviewDate { get; set; }

    public string FReviewContent { get; set; }

    public virtual TMember FMember { get; set; }
}