// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TMemberShoppingCartHomestay
{
    public int FShoppingCartHomestayID { get; set; }

    public int FShoppingCartID { get; set; }

    public byte? FPickupLocationID { get; set; }

    public byte? FDropoffLocationID { get; set; }

    public DateTime FStartDatetime { get; set; }

    public DateTime FEndDatetime { get; set; }

    public virtual TLocation FDropoffLocation { get; set; }

    public virtual TLocation FPickupLocation { get; set; }

    public virtual TMemberShoppingCart FShoppingCart { get; set; }
}