// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TMemberLoginType
{
    public byte FLoginTypeID { get; set; }

    public string FLoginTypeName { get; set; }

    public virtual ICollection<TMemberLoginRecord> TMemberLoginRecords { get; set; } = new List<TMemberLoginRecord>();

    public virtual ICollection<TMemberThirdPartyAccount> TMemberThirdPartyAccounts { get; set; } = new List<TMemberThirdPartyAccount>();
}