// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TProductHomestayRoom
{
    public int FHomestayRoomID { get; set; }

    public bool FIsPublished { get; set; }

    public int FHomestayID { get; set; }

    public string FRoomCode { get; set; }

    public byte FBathroomCount { get; set; }

    public byte FToiletCount { get; set; }

    public byte FQueenBedCount { get; set; }

    public byte FSingleBedCount { get; set; }

    public string FMaxCapacity { get; set; }

    public bool FIsCleaned { get; set; }

    public DateTime FLastCleanDatetime { get; set; }

    public virtual TProductHomestay FHomestay { get; set; }

    public virtual ICollection<TProductHomestayPrice> TProductHomestayPrices { get; set; } = new List<TProductHomestayPrice>();
}