// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TProductStorage
{
    public int FStorageID { get; set; }

    public byte FEquipmentCategoryID { get; set; }

    public decimal FStoragePrice { get; set; }

    public virtual TProductEquipmentCategory FEquipmentCategory { get; set; }
}