// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TProductTagMapping
{
    public int FProductTagMappingID { get; set; }

    public string FProductType { get; set; }

    public int FProductID { get; set; }

    public string FProductCode { get; set; }

    public int FTagID { get; set; }

    public virtual TTag FTag { get; set; }
}