// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TProductCoursePrice
{
    public int FCoursePriceID { get; set; }

    public int FCourseID { get; set; }

    public string FCourseCombo { get; set; }

    public decimal FCoursePrice { get; set; }

    public virtual TProductCourse FCourse { get; set; }
}