// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TProductHomestay
{
    public int FHomestayID { get; set; }

    public string FHomestayCode { get; set; }

    public string FHomestayName { get; set; }

    public string FDescription { get; set; }

    public byte FAddressID { get; set; }

    public virtual TLocation FAddress { get; set; }

    public virtual ICollection<TProductHomestayRoom> TProductHomestayRooms { get; set; } = new List<TProductHomestayRoom>();
}