// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TProductShuttlePrice
{
    public int FShuttlePriceID { get; set; }

    public byte FShuttleID { get; set; }

    public byte FPickupLocationID { get; set; }

    public byte FDropoffLocationID { get; set; }

    public decimal FShuttlePrice { get; set; }

    public virtual TLocation FDropoffLocation { get; set; }

    public virtual TLocation FPickupLocation { get; set; }

    public virtual TProductShuttle FShuttle { get; set; }
}