// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TCoachPrice
{
    public int FCoachPriceID { get; set; }

    public byte FCoachLevelID { get; set; }

    public bool FIsSixHours { get; set; }

    public decimal FCoachPrice { get; set; }

    public virtual TCoachLevel FCoachLevel { get; set; }
}