// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TMemberShoppingCart
{
    public int FShoppingCartID { get; set; }

    public int FMemberID { get; set; }

    public string FProductType { get; set; }

    public int FProductID { get; set; }

    public decimal FPrice { get; set; }

    public string FRemark { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual ICollection<TMemberShoppingCartCourse> TMemberShoppingCartCourses { get; set; } = new List<TMemberShoppingCartCourse>();

    public virtual ICollection<TMemberShoppingCartHomestay> TMemberShoppingCartHomestays { get; set; } = new List<TMemberShoppingCartHomestay>();
}