// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TMemberShoppingCartCourse
{
    public int FShoppingCartCourseID { get; set; }

    public int FShoppingCartID { get; set; }

    public byte FLocationID { get; set; }

    public byte FDays { get; set; }

    public byte FPeopleCount { get; set; }

    public virtual TLocation FLocation { get; set; }

    public virtual TMemberShoppingCart FShoppingCart { get; set; }
}