// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TOrderDetail
{
    public int FOrderDetailID { get; set; }

    public int FOrderID { get; set; }

    public string FProductType { get; set; }

    public int FProductID { get; set; }

    public decimal FOrderDetailAmount { get; set; }

    public string FRemarks { get; set; }

    public virtual TOrder FOrder { get; set; }

    public virtual ICollection<TOrderDetailCourse> TOrderDetailCourses { get; set; } = new List<TOrderDetailCourse>();

    public virtual ICollection<TOrderDetailHomestay> TOrderDetailHomestays { get; set; } = new List<TOrderDetailHomestay>();
}