// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TOrderPaymentRecord
{
    public int FPaymentRecordID { get; set; }

    public int FOrderID { get; set; }

    public byte FPaymentStatusID { get; set; }

    public byte FPaymentMethodID { get; set; }

    public DateTime FPaymentDatetime { get; set; }

    public decimal FPaymentAmount { get; set; }

    public short? FBankID { get; set; }

    public string FCardholderName { get; set; }

    public string FCardNumber { get; set; }

    public string FCardExpiryYear { get; set; }

    public string FCardExpiryMonth { get; set; }

    public virtual TOrder FOrder { get; set; }

    public virtual TOrderPaymentMethod FPaymentMethod { get; set; }

    public virtual TOrderPaymentStatus FPaymentStatus { get; set; }
}