// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TOrderPaymentStatus
{
    public byte FPaymentStatusID { get; set; }

    public string FPaymentStatusName { get; set; }

    public virtual ICollection<TOrderPaymentRecord> TOrderPaymentRecords { get; set; } = new List<TOrderPaymentRecord>();
}