// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TProductEquipmentCategory
{
    public byte FEquipmentCategoryID { get; set; }

    public string FEquipmentCategoryName { get; set; }

    public virtual ICollection<TProductEquipment> TProductEquipments { get; set; } = new List<TProductEquipment>();

    public virtual ICollection<TProductStorage> TProductStorages { get; set; } = new List<TProductStorage>();
}