// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Niseko.Server.Models;

public partial class TProductImage
{
    public int FProductImageID { get; set; }

    public string FProductType { get; set; }

    public int FProductID { get; set; }

    public string FImage { get; set; }
}