// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Appointment.Server.Models;

public partial class WBEAURE
{
    public int WBID { get; set; }

    public string ACUTE { get; set; }

    public string CNUM { get; set; }

    public string SERNO { get; set; }

    public string SDATE { get; set; }

    public string CURENO { get; set; }

    public string CURENAME { get; set; }

    public string RDATE { get; set; }

    public string RTIME { get; set; }

    public string OPERUSER { get; set; }

    public string CDOC { get; set; }

    public string CDOCS { get; set; }

    public string CDOCP { get; set; }

    public decimal? CURECNT { get; set; }

    public decimal? CURECNTS { get; set; }

    public string CSTAT { get; set; }

    public string CMESS { get; set; }

    public string CUPDATE { get; set; }
}