// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NunitTrain1.Models;

public partial class macTestContext : DbContext
{
    public macTestContext()
    {
    }

    public macTestContext(DbContextOptions<macTestContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=台南SERVER\\YIFEI;Initial Catalog=macTest;User ID=YIFEI2;Password=YIFEI21234;Connect Timeout=30;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.cid).HasName("PK__Customer__D837D05FF6FC9722");

            entity.HasIndex(e => e.email, "UQ__Customer__AB6E6164EF60CAD8").IsUnique();

            entity.Property(e => e.email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.oid).HasName("PK__Orders__C2FFCF134C0EA899");

            entity.HasOne(d => d.customer_c).WithMany(p => p.Orders)
                .HasForeignKey(d => d.customer_cid)
                .HasConstraintName("FK__Orders__customer__276EDEB3");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.oiid).HasName("PK__OrderIte__4DCED7D604AB5705");

            entity.Property(e => e.price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.product_name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.order_o).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.order_oid)
                .HasConstraintName("FK__OrderItem__order__2A4B4B5E");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}