// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NunitTrain1.Models;

public partial class OrderItem
{
    public int oiid { get; set; }

    public int? order_oid { get; set; }

    public string product_name { get; set; }

    public int quantity { get; set; }

    public decimal price { get; set; }

    public virtual Order order_o { get; set; }
}