// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NunitTrain1.Models;

public partial class Order
{
    public int oid { get; set; }

    public int? customer_cid { get; set; }

    public DateOnly order_date { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Customer customer_c { get; set; }
}