// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Appointment.Server.Models;

public partial class WBRSTOR
{
    public string CNUM { get; set; }

    public string CNAME { get; set; }
}