// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Appointment.Server.Models;

public partial class WCUSTOM
{
    public string CNUM { get; set; }

    public string CNAME { get; set; }

    public string CBIRTH { get; set; }

    public string CMOBILE { get; set; }
}