// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Appointment.Server.Models;

public partial class WSUBSAM
{
    public int SID { get; set; }

    public string CNUM { get; set; }

    public string SERNO { get; set; }

    public string SDATE { get; set; }

    public string CNAME { get; set; }

    public string CURENO { get; set; }

    public string CURENAME { get; set; }

    public decimal CURECNT { get; set; }

    public decimal CURECNTS { get; set; }

    public decimal? SUBQTY { get; set; }

    public decimal? SUBCNT { get; set; }
}