// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Appointment.Server.Models;

public partial class WUSER
{
    public string UEMPDEG { get; set; }

    public string USERID { get; set; }

    public string PASSWD { get; set; }

    public string USERNAME { get; set; }

    public string UOUTDATE { get; set; }

    public string SHOPNO { get; set; }
}